### ISSUE TITLE
Error finding provider

### ISSUE THREAD

**Issue by designermonkey** [tenstad/terraform-provider-remote#116]
I used this only recently (within a month), but now it seems to have stopped working.

```
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│ 
│ Error while installing tenstad/remotefile v0.1.0: could not query provider
│ registry for registry.terraform.io/tenstad/remotefile: failed to retrieve
│ authentication checksums for provider: 404 Not Found returned from 
╵
```

Above is the error I get when trying to init a terragrunt and terraform project using this provider. Provider settings below:

```hcl
terraform {
  required_version = ">= 1.0"

  required_providers {
    remotefile = {
      source = "tenstad/remotefile"
      version = "0.1.0"
    }
  }
}
```

Is this provider still available?

**Comment by tenstad** [comment]
Hi, i think the `remotefile` key and `source` value is incorrect. Could you try the following?

```terraform
terraform {
  required_providers {
    remote = {
      source = "tenstad/remote"
      version = "0.1.0"
    }
  }
}
```

**Comment by tenstad** [comment]
The issue here is that I am unable to remove the old provider from terraform registry. Currently both `remotefile` and `remote` are visible, and both are seemingly connected to this GitHub repo. https://registry.terraform.io/namespaces/tenstad

**Comment by designermonkey** [comment]
That worked thanks.
