### ISSUE TITLE
Why is version 0.1.1 not yet published on the public terraform registry?

### ISSUE THREAD

**Issue by masterfix** [tenstad/terraform-provider-remote#119]
I need the new timeout feature added in version 0.1.1. It seems that this version is not yet deployed on the terraform registry. The latest version there is 0.1.0. Is there a reason why it is not yet published?

**Comment by tenstad** [comment]
> Could not find all platform assets for this release yet (0.1.1) — 22 days ago
> no valid platform assets found

Will look into it, thanks!

**Comment by tenstad** [comment]
Having some issues with `hashicorp/ghaction-import-gpg@v2.1.0`

> Run hashicorp/ghaction-import-gpg@v2.1.0
Run gpg-agent --daemon --default-cache-ttl 7200
gpg-agent[1671]: directory '/home/runner/.gnupg' created
gpg-agent[1671]: directory '/home/runner/.gnupg/private-keys-v1.d' created
gpg-agent: a gpg-agent is already running - not starting a new one
Error: Process completed with exit code 2.

Uploaded the release files manually instead, please check https://registry.terraform.io/providers/tenstad/remote/0.1.1 now

**Comment by masterfix** [comment]
It is no published and working. Thanks for the quick reaction!
