### ISSUE TITLE
Unable to use the provider on Apple Silicon

### ISSUE THREAD

**Issue by timbrd** [tenstad/terraform-provider-remote#23]
Hi,

I just switched from an intel MacBook to Apple Silicon. Unfortunately your plugin does not work anymore, terraform does not find a version which has been built for darwin_arm64:

```bash
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/tenstad/remote v0.0.21 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms
│ supported.
```

Is there are way you extend the plattform list or can I build the provider myself?

**Comment by tenstad** [comment]
Thank you for creating an issue. Appears darwin/arm64 is only built on go version 1.16 and above. Current version is 1.15, but I think upgrading should be possible. Will look into it 😄 

https://goreleaser.com/deprecations/#builds-for-darwinarm64

**Comment by tenstad** [comment]
@timbrd please test the v0.0.22 release  
https://github.com/tenstad/terraform-provider-remote/releases/tag/v0.0.22

**Comment by timbrd** [comment]
Awesome, thanks for fixing it so fast!

I have just tested v0.0.22 and can confirm that it is working on my M1 Pro.
