### ISSUE TITLE
Public key auth fails in pipeline, although not locally

### ISSUE THREAD

**Issue by tenstad** [tenstad/terraform-provider-remote#36]
https://github.com/tenstad/terraform-provider-remote/runs/4971214025?check_suite_focus=true

**Comment by akelge** [comment]
For me the connection fails even locally
```
data "remote_file" "kubeconfig" {
  conn {
    host  = aws_instance.rke2-master[0].private_ip
    user  = var.ssh_user
    private_key_path = pathexpand(var.ssh_key_path)
    sudo = true
  }

  path = "..."
}```

result is
```
Error: error while opening remote client: couldn't establish a connection to the remote server: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
│ 
│   with module.cluster1.data.remote_file.kubeconfig,
│   on ../../modules/rke2/main.tf line 117, in data "remote_file" "kubeconfig":
│  117: data "remote_file" "kubeconfig" {
```
on server I can see
```
 Connection closed by authenticating user XXXXXX 10.1.1.182 port 13443 [preauth]
 ```
 
 I tried to use `private_key_path`, but also `private_key` using `file(var.ssh_key_path)` as value, also reading the ssh key into a `data`, then passing the `.content` to `private_key`, with no success.

**Comment by tenstad** [comment]
Hi @akelge. What does the server log when you try to ssh into it using the same private key?

**Comment by akelge** [comment]
On my laptop:
`ssh -i ~/.ssh/keys/<key_name> XXXX@cluster1-master0.yyy.lan`

on server:
```
Mar 23 10:29:58 cluster1-master0 sshd[282395]: Accepted publickey for XXXX from 10.1.1.182 port 39824 ssh2: ED25519 SHA256:<random_chars>
Mar 23 10:29:58 cluster1-master0 sshd[282395]: pam_unix(sshd:session): session opened for user XXXX by (uid=0)
```

**Comment by akelge** [comment]
Nevermind, found the issue, it's on my side: the key I am using is a `RSA PRIVATE KEY`, not an `OPENSSH PRIVATE KEY`. It seems `ssh` command is not picky about it, while `ssh` go client chokes (correctly) on it
