### ISSUE TITLE
Allow specifying owner and group

### ISSUE THREAD

**Issue by joshuaspence** [tenstad/terraform-provider-remote#42]
Currently the remote file ends up being owned by the SSH user. It would be useful, especially in combination with `sudo = true` if the file could be `chown`ed to be owned by another user/group.

**Comment by tenstad** [comment]
Nice feature! Would you like to propose a pull request? I am devoting my time to `conn` defaulting and exposed sensitive fields atm. Will probably get to this later if not already resolved.

**Comment by joshuaspence** [comment]
Yeah I can submit a PR

**Comment by tenstad** [comment]
@joshuaspence would you still like to create a PR, or should I look into it?

**Comment by bjw-s** [comment]
I've just submitted a PR to implement this feature :)
