### ISSUE TITLE
Add a default connection 

### ISSUE THREAD

**Issue by Senth** [tenstad/terraform-provider-remote#7]
### Problem
I use Terraform to configure my local server and thus have to repeat the same conn {...} input for every remote file.

### Solution
Add an optional default provider in the connection. When a default connection has been set, you don't have to specify a conn variable for resources and data sources.
```terraform
provider "remotefile" {
  default_conn {
    host        = "foo.com"
    port        = 22
    username    = "foo"
    sudo        = true
    private_key = "<ssh private key>"
  }
}
```

### Alternative Solution
Add the ability to create different configurations identified by key. This solution has the ability to easily connect to different servers if necessary. Alternatively `conn = foo` could be `conn_name = foo` or similar.
```terraform
provider "remotefile" {
  conns = [
    "foo" : {
      host        = "foo.com"
      port        = 22
      username    = "foo"
      sudo        = true
      private_key = "<ssh private key>"
    }
  ]
}

resource "remotefile" "foo" {
  path = "/tmp/foo.txt"
  conn = "foo"
  ...
}
```

**Comment by tenstad** [comment]
Thank you for your suggestions! I think the first one makes a lot of sense, and that the benefit of creating multiple configurations can be solved with aliases: https://www.terraform.io/docs/language/providers/configuration.html#alias-multiple-provider-configurations

The current solution would be group all files with the same connection in a local variable and to use `for_each` to iterate over the files.
```hcl
resource "remotefile" "server1" {
  for_each = local.files

  conn { ... }

  path = each.key
  content = each.value
}
```

**Comment by tenstad** [comment]
I have now added `conn` to the provider configuration as well, as a default connection. (note that I have also renamed the provider)

Seems to be working, but changing the `host` in the provider's `conn` is not forcing a replacement of the file resource. It results in terraform not finding the file on the new host when refreshing the state.

**Comment by tenstad** [comment]
I have created a followup issue https://github.com/tenstad/terraform-provider-remote/issues/13.

**Comment by Senth** [comment]
Thanks a bunch! 😃
